acquia_contenthub_publisher.exclude_settings:
  type: config_object
  label: 'Acquia ContentHub entity type or bundle exclude settings'
  mapping:
    exclude_entity_types:
      type: sequence
      label: 'Entity types to exclude'
      sequence:
        type: string
        label: 'Entity type'
    exclude_bundles:
      type: sequence
      label: 'Bundles to exclude'
      sequence:
        type: string
        label: 'Bundle'

acquia_contenthub_publisher.features:
  type: config_object
  label: 'Acquia ContentHub Publisher features'
  mapping:
    paragraphs_unchanged_disable_revision:
      type: boolean
      label: 'Enforce paragraph to have same revision, if entity unchanged'
