---
type: default
team: content-hub
group: drupal-cloud
service: acquia_contenthub

# Example Acquia CI configuration.
#
# The configuration files in the .acquia directory will cover ORCA integration for most packages almost
# without modification. Use as follows:
#
# 1. Copy the .acquia directory to your package root:
#
#    $ cp -R example/.acquia ../my_package/.acquia
#
# 2. Change the team and service values for your package and change environment_image.build_args.secrets as necessary.
#    No other changes are strictly necessary for a basic integration.
#
# 3. Review the other comments in the file for additional configuration options.
#
# 4. Strip the (now unnecessary) comments:
#
#    $ sed -i'.bak' -e '/^[[:blank:]]*#/d;s/#.*//' pipeline.yaml && rm pipeline.yaml.bak
#
# 5. Make necessary changes in /my_package/.acquia/Dockerfile.ci
#
# For advanced needs,
# @see https://github.com/acquia/orca/blob/main/docs/advanced-usage.md

# The environment container image is used to prepare code versions
# and tooling for tests during pre, post and build stages.
environment_image:
  file: ".acquia/Dockerfile.ci"
  context: "."

_orca_steps: &orca_steps
  steps:
    # The following operations should happen on the RAM disk:
    # 1. All PHP code that gets executed during tests. (Because most PHP
    #    code will only be executed once, making PHP's built-in OPCache
    #    ineffective. Acquia CI does not handle massive disk I/O
    #    concurrency well, and that is exactly what happens when executing
    #    multiple test jobs each testing a PHP application with many files
    #    on disk: just Drupal core alone already requires a significant
    #    number of files to be read from disk.
    # 2. SQLite database. The SQLite database lives on disk. Executing
    #    Drupal test suites tends to trigger many database queries, which
    #    in turn result in disk I/O.
    #    When not paying attention to these points, ORCA test suites can
    #    easily be significantly slower on Acquia CI than on TravisCI
    #    (which has a different disk I/O model). But when taken into
    #    account, ORCA on Acquia CI tends to *FAST*!
    #    If you were to run out of space on the RAM disk, simply file a
    #    DEVOPS ticket to bump the memory limit for your project; they will
    #    provision you more.
    # @see https://docs.docker.com/storage/tmpfs/
    # @see https://github.com/acquia/devops-pipeline/pull/275
    -
      - cp -ar /acquia /ramfs  &&  df -hT
      - export CI_WORKSPACE=/ramfs${CI_WORKSPACE}
    - |
      cd /ramfs${CI_WORKSPACE}
      ../orca/bin/ci/before_install.sh && error=false || error=true
      if [ "$error" = "false" ]; then
        ./tests/ci/before_install.sh
      fi
    - |
      cd /ramfs${CI_WORKSPACE}
      # Switch to PHP8.1. The version will depend on the version(s) installed in your Dockerfile.
      # The template provides version 8.1.
      if [ "$JENKINS_PHP_VERSION" = 8.1 ]; then
        update-alternatives --install /usr/local/bin/php php /usr/bin/php8.1 80
        php -v
      fi
    - |
      cd /ramfs${CI_WORKSPACE}
      ../orca/bin/ci/install.sh && error=false || error=true
      if [ "$error" = "false" ]; then
        ./tests/ci/install.sh
      fi
    -
      - cd /ramfs${CI_WORKSPACE}
      - ../orca/bin/ci/before_script.sh
    - |
      cd /ramfs${CI_WORKSPACE}
      ../orca/bin/ci/script.sh && error=false || error=true
      if [ "$error" = "false" ]; then
        ./tests/ci/script.sh
      fi
      if [ "$error" = "true" ]; then
        echo "Running after failure";
        ../orca/bin/ci/after_failure.sh;
        if [ "$ALLOWED_FAILURE" = "true" ]; then
          exit 0;
        else
          exit 1;
        fi
      else
        echo "Running after success";
        ../orca/bin/ci/after_success.sh;
      fi
    - |
      if [ "$ORCA_COVERAGE_ENABLE" = true ]; then
        cd /ramfs${CI_WORKSPACE}
        php .acquia/fixup-xml-paths.php /acquia/acquia_contenthub/clover.xml
        php .acquia/fixup-xml-paths.php /acquia/acquia_contenthub/junit.xml
      fi

_orca_job: &orca_job
  <<: *orca_steps
_orca_job_allow_failures: &orca_job_allow_failures
  - ignore_failures: true
    <<: *orca_steps

# -- Continuous Integration --
# Pre-build runs after building the environment image, and relies on it to
# run its sub-stages' steps inside of the environment container.
pre_build:
  static_code_analysis:
    - args: --env ORCA_JOB=STATIC_CODE_ANALYSIS
      <<: *orca_job
  integrated_test_on_oldest_supported:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_OLDEST_SUPPORTED
      <<: *orca_job
  integrated_test_on_latest_lts:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_LATEST_LTS
      <<: *orca_job
  integrated_test_on_prev_minor:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_PREVIOUS_MINOR
      <<: *orca_job
  integrated_test_from_prev_minor:
    - args: --env ORCA_JOB=INTEGRATED_UPGRADE_TEST_FROM_PREVIOUS_MINOR
      <<: *orca_job
  isolated_test_on_current:
    - args: --env ORCA_JOB=ISOLATED_TEST_ON_CURRENT --env ORCA_COVERAGE_ENABLE=true --env ORCA_COVERAGE_CLOVER=/acquia/acquia_contenthub/clover.xml --env ORCA_JUNIT_LOG=/acquia/acquia_contenthub/junit.xml
      ca_data: /acquia
      <<: *orca_job
  isolated_test_on_current_php8:
    - args: --env ORCA_JOB=ISOLATED_TEST_ON_CURRENT --env JENKINS_PHP_VERSION=8.1
      <<: *orca_job
  integrated_test_on_current:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_CURRENT
      <<: *orca_job
  integrated_test_to_next_minor:
    - args: --env ORCA_JOB=INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR
      <<: *orca_job
  integrated_test_to_next_minor_dev:
    - args: --env ORCA_JOB=INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR_DEV --env ALLOWED_FAILURE=true
      <<: *orca_job
  isolated_test_on_current_dev:
    - args: --env ORCA_JOB=ISOLATED_TEST_ON_CURRENT_DEV
      <<: *orca_job
  integrated_test_on_current_dev:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_CURRENT_DEV
      <<: *orca_job
  loose_deprecated_code_scan:
    - args: --env ORCA_JOB=LOOSE_DEPRECATED_CODE_SCAN --env ALLOWED_FAILURE=true
      <<: *orca_job
  strict_deprecated_code_scan:
    - args: --env ORCA_JOB=STRICT_DEPRECATED_CODE_SCAN --env ALLOWED_FAILURE=true
      <<: *orca_job
  deprecated_code_scan_w_contrib:
    - args: --env ORCA_JOB=DEPRECATED_CODE_SCAN_W_CONTRIB --env ALLOWED_FAILURE=true
      <<: *orca_job
  isolated_test_on_next_minor:
    - args: --env ORCA_JOB=ISOLATED_TEST_ON_NEXT_MINOR
      <<: *orca_job
  integrated_test_on_next_minor:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR
      <<: *orca_job
  isolated_test_on_next_minor_dev:
    - args: --env ORCA_JOB=ISOLATED_TEST_ON_NEXT_MINOR_DEV --env ALLOWED_FAILURE=true
      <<: *orca_job
  integrated_test_on_next_minor_dev:
    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR_DEV --env ALLOWED_FAILURE=true
      <<: *orca_job

  # Uncomment the following four jobs to enable the corresponding tests once
  # the next major version of Drupal core has an alpha release or earlier.
  # Until then it's wasteful to use CI jobs on them, even if they exit early.
  # isolated_test_on_next_major_latest_minor_beta_later
  #   - args: --env ORCA_JOB=ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
  #     <<: *orca_steps
  # integrated_test_on_next_major_latest_minor_beta_later
  #   - args: --env ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
  #     <<: *orca_steps
  # isolated_test_on_next_major_latest_minor_dev
  #   - args: --env ORCA_JOB=ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
  #     <<: *orca_steps
  # integrated_test_on_next_major_latest_minor_dev
  #   - args: --env ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
  #     <<: *orca_steps

  isolated_upgrade_test_to_next_major_beta_later:
    - args: --env ORCA_JOB=ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_BETA_OR_LATER
      <<: *orca_job
  isolated_upgrade_test_to_next_major_dev:
    - args: --env ORCA_JOB=ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_DEV --env ALLOWED_FAILURE=true
      <<: *orca_job

  security_composition_analysis:
    required: true

  # code_analysis is option for sonarqube if you have group and team name added on top of pipeline.yaml
  # https://github.com/acquia/devops-pipeline/commit/b707527f72a56e352e0975ac9482504e34603b7c
  # keeping it commented for future reference in case we need to override the default values provided by sonarqube.
  code_analysis:
    required: true
    project_key: acquia.drupal-cloud.content-hub:acquia_contenthub
  #  quality_gate:
  #    wait_for_quality_gate: true
  #    max_time_limit: 2
  #    abort_pipeline: true

# -- Slack Bot Integration --
notify:
  channel: ch-modules-eng
  on_success: change
  on_failure: always
