#!/bin/bash

set -e
# Check to see if this is a tagged commit.
COMMIT_TAG=$(git tag --points-at HEAD)

blt artifact:deploy --commit-msg "Automated commit by Acquia CI for Build ${BUILD_NUMBER}" --branch "${GIT_BRANCH}-build" --no-interaction --verbose

if [[ $COMMIT_TAG ]]; then
  cd deploy
  git tag ${COMMIT_TAG}
  git remote | xargs -L1 -I R git push R ${COMMIT_TAG}
fi

set +e
