#!/bin/bash

set -e

# For private repos, Composer won't respect .gitattributes for ignoring files
# when creating an artifact unless a github oauth token is configured, which is
# a little dangerous in a travis file. Manually delete unti ACMS goes GA and the
# repos are public.
if [ "$CI" ]; then
  echo "Removing files that should have been excluded by Composer."
  cat scripts/sanitize-list.txt | xargs rm
fi

set +e
