#!/usr/bin/env bash

set -e

# Allow MySQL to finish starting.
sleep 3

export PATH=${COMPOSER_BIN}:$PATH

# Create fake mailer.
echo 'max_execution_time = 120' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
# Set PHP memory limit to appease ACMS' sadistic appetites.
echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Set git info.
git config --global user.name "Travis-CI"
git config --global user.email "noreply@travis-ci.com"

set +e
